_wandb:
    value:
        cli_version: 0.23.1
        e:
            9411nkm4elnecu895xibxol27s3tbyjd:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "23622320128"
                args:
                    - --policy-type
                    - flow
                codePath: hw1/src/hw1_imitation/train.py
                codePathLocal: src/hw1_imitation/train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "387584819200"
                email: qpkong27@gmail.com
                executable: /Users/qpkong/Desktop/courses/CS285/homework_spring2026/hw1/.venv/bin/python3
                git:
                    commit: b1ffc4d99055a14ff37f0111204e1eac0f4a6fb0
                    remote: https://github.com/Kqp1227/homework_spring2026
                host: qpkongs-MacBook-Air.local
                memory:
                    total: "25769803776"
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/qpkong/Desktop/courses/CS285/homework_spring2026/hw1/src/hw1_imitation/train.py
                python: CPython 3.11.14
                root: /Users/qpkong/Desktop/courses/CS285/homework_spring2026/hw1
                startedAt: "2026-02-11T10:42:33.363741Z"
                writerId: 9411nkm4elnecu895xibxol27s3tbyjd
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 128
chunk_size:
    value: 8
data_dir:
    value: data
eval_interval:
    value: 10000
exp_name:
    value: null
flow_num_steps:
    value: 10
hidden_dims:
    value:
        - 256
        - 256
        - 256
log_interval:
    value: 100
lr:
    value: 0.0003
num_epochs:
    value: 400
num_video_episodes:
    value: 5
policy_type:
    value: flow
seed:
    value: 42
video_size:
    value:
        - 256
        - 256
wandb_project:
    value: hw1-imitation
weight_decay:
    value: 0
